FROM node:17-alpine AS builder

WORKDIR /app
COPY ["package.json", "yarn.lock" ,"./"]
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM nginx:stable-alpine AS server
# COPY ../nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/build /usr/share/nginx/html