version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
  node-app:
    build:
      context: ./backend
      target: prod
    environment:
      - NODE_ENV=production
    command: node build/src/app.js
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
  certbot:
    container_name: certbot
    image: certbot/certbot:v1.9.0
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email contact@smartdollarz.com --agree-tos --no-eff-email --staging -d smartdollarz.com  -d smartdollarz.com
    restart: unless-stopped

volumes:
  web-root:
  certbot-etc:
  certbot-var:
