version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  node-app:
    build:
      context: ./backend
      target: base
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
  nginx:
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
