version: '3'
services:
  react-app:
    container_name: react-app
    depends_on:
      - node-app
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  node-app:
    container_name: node-app
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    restart: unless-stopped
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '6000:27017'
    env_file:
      - ./backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'edemziddah'
      MONGO_INITDB_ROOT_PASSWORD: 'pass1234'
    volumes:
      - mongo-db:/data/db
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - node-app
      - react-app
    restart: unless-stopped
volumes:
  mongo-db:
  redis:
